### ISSUE TITLE
Arsenal quantity UI bug

### ISSUE THREAD

**Issue by evertiro** [KAT-Advanced-Medical/KAM#365]
**Arma 3 Version:** `stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- For several items, there is an odd UI bug in the ACE Arsenal. When you add them to an inventory, they add successfully, but the UI locks at 1. As a result, you can only _remove_ one without opening your inventory and literally dropping them on the ground. This appears to affect the following items:

- Ammonium Carbonate
- Caffeine bottle
- First Aid Kit
- Painkillers
- Pervitin capsule
- Portable Oxygen Tank (150L)
- Portable Oxygen Tank (300L)

**Steps to reproduce:**
- Open ACE Arsenal, click the plus sign to add any of the above to your inventory.

**Where did the issue occur?**
- Self-Hosted Multiplayer
- Singleplayer

**Placed Modules:**
- None

**RPT log file:**
- [gist](https://gist.github.com/evertiro/6d91573a581494d9f46a67def2500419)

**Comment by BlueTheKing** [comment]
Because these items have to be magazines to be used for their intended purpose they cannot be outside the magazine tab in the arsenal, so dummy items exist instead which are turned into magazines once they are in your inventory, this does mean you can't remove these items because they have been replaced by the magazine variant of it.

You can avoid this by adding all of these items in the magazine tab instead of the medical tab.

The FAK gets replaced with medical items as part of ace, this can be changed in the cba settings.

**Comment by evertiro** [comment]
Yea the FAK replacement isn't working for me either with the above setup. Also, that's a weird requirement. Gotta love modding.
